[build]
target = "i686-unknown-none.json"
rustflags = [
    "-C", "link-arg=--script=kernel.ld",
    "-C", "relocation-model=static",
    "-C", "strip=debuginfo",
]

[unstable]
build-std = ["core", "alloc", "compiler_builtins", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]