[build]
target = "i686-unknown-none.json"
rustflags = [
    "-C", "link-arg=--script=kernel.ld",
    "-C", "relocation-model=static",
]

[unstable]
build-std = ["core", "compiler_builtins", "panic_abort", "alloc"]
build-std-features = ["compiler-builtins-mem"]
