#!/usr/bin/env python3
"""Generate kernel64/src/io/font.rs from a Linux console font (PSF1/PSF2).

The kernel's framebuffer console needs a bitmap font; instead of hand-drawing
glyphs we lift one from the host's console fonts and commit the generated Rust
file, so the build itself has no font dependency.

    tools/mkfont.py /usr/share/consolefonts/Lat15-VGA16.psf.gz > kernel64/src/io/font.rs

Only printable ASCII (32..126) is kept: 95 glyphs, `height` bytes each, one bit
per pixel with the most significant bit leftmost.
"""
import gzip
import struct
import sys

FIRST, LAST = 32, 126


def load(path):
    with gzip.open(path, "rb") as fh:
        data = fh.read()
    if data[:2] == b"\x36\x04":
        mode, charsize = data[2], data[3]
        width, height = 8, charsize
        count = 512 if (mode & 1) else 256
        # PSF1 puts an optional unicode table right after the 4-byte header, but
        # some Debian fonts set that bit while storing the table *after* the
        # glyphs.  Probe the three candidate offsets and pick the one where
        # glyph 32 is blank and glyph 65 looks like an 'A'.
        offset = 4
        for cand in (4, 4 + 512, 4 + 1024):
            space = data[cand + 32 * charsize: cand + 33 * charsize]
            letter = data[cand + 65 * charsize: cand + 66 * charsize]
            if not any(space) and sum(bin(b).count("1") for b in letter) >= 8:
                offset = cand
                break
        glyphs = [data[offset + i * charsize: offset + (i + 1) * charsize] for i in range(count)]
        return width, height, glyphs
    if data[:4] == b"\x72\xb5\x4a\x86":
        _, _ver, _hdr, flags, length, charsize, height, width = struct.unpack("<4sIBBIIII", data[:32])
        offset = 32
        if flags & 1:
            offset += 4 * length
        if flags & 2:
            # Unicode table: skip it (we only need the low 128 glyph slots).
            unicode_len = struct.unpack_from("<I", data, offset)[0]
            offset += 4 + unicode_len
        glyphs = [data[offset + i * charsize: offset + (i + 1) * charsize] for i in range(length)]
        return width, height, glyphs
    raise SystemExit(f"{path}: not a PSF1/PSF2 font")


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/consolefonts/Lat15-VGA16.psf.gz"
    width, height, glyphs = load(path)
    if width != 8:
        raise SystemExit(f"only 8-pixel-wide fonts are supported, got {width}")
    if len(glyphs) <= LAST:
        raise SystemExit("font does not cover printable ASCII")

    out = []
    out.append("//! 8x%d bitmap font for the framebuffer console." % height)
    out.append("//!")
    out.append("//! Generated by `tools/mkfont.py` from %s — do not edit by hand." % path)
    out.append("")
    out.append("pub const FONT_WIDTH: usize = %d;" % width)
    out.append("pub const FONT_HEIGHT: usize = %d;" % height)
    out.append("pub const FONT_FIRST: u8 = %d;" % FIRST)
    out.append("pub const FONT_LAST: u8 = %d;" % LAST)
    out.append("")
    out.append("/// One `FONT_HEIGHT`-byte column-major-by-row bitmap per glyph.")
    out.append("pub static FONT: [[u8; FONT_HEIGHT]; %d] = [" % (LAST - FIRST + 1))
    for code in range(FIRST, LAST + 1):
        g = glyphs[code]
        rows = ", ".join("0x%02x" % b for b in g[:height])
        ch = chr(code)
        if ch == "\\":
            ch = "\\\\"
        out.append("    [%s], // %d %r" % (rows, code, ch))
    out.append("];")
    out.append("")
    print("\n".join(out))


if __name__ == "__main__":
    main()
