[workspace]
resolver = "2"
members = [
    "lib/rondos-abi",
    "lib/rondos-rt",
    "apps/init",
    "apps/selftest",
    "apps/crash",
    "apps/spin",
    "apps/echo",
    "apps/heap",
    "apps/physcheck",
]

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"
opt-level = 3
lto = true
codegen-units = 1
